cmake_minimum_required(VERSION 3.29)
project(Example4 CXX)
set(CMAKE_CXX_STANDARD 23)

if (NOT DEFINED OUT_PATH)
    set(OUT_PATH "${CMAKE_BINARY_DIR}")
endif()
if (VERBOSE)
    add_compile_definitions(IS_VERBOSE)
endif()
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../include")

if (GENERATE_BOOTSTRAP)
    if (NOT DEFINED BOOTSTRAPPER_BUILD_DIR)
        set(BOOTSTRAPPER_BUILD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/build-bootstrapper")
    endif()
    add_executable(bootstrapper main.cpp)
    target_compile_definitions(bootstrapper PRIVATE
            IS_BOOTSTRAP="${GENERATE_BOOTSTRAP}"
            OUT_PATH="${BOOTSTRAPPER_BUILD_DIR}"
    )
else()
    enable_language(ASM_NASM)
    if (NOT EXISTS "${OUT_PATH}/bootstrap.txt")
        message(FATAL_ERROR "Please build and run the generator half first.")
    else()
        file(STRINGS "${OUT_PATH}/bootstrap.txt" FILE_STEM)
        list(GET FILE_STEM 0 FILE_STEM)
    endif()
    add_library(${FILE_STEM} SHARED main.cpp "${OUT_PATH}/${FILE_STEM}.asm")
    set_target_properties(${FILE_STEM} PROPERTIES
            LINK_FLAGS "/DEF:\"${OUT_PATH}/${FILE_STEM}.def\""
    )
    target_compile_definitions(${FILE_STEM} PRIVATE OUT_PATH="${OUT_PATH}")
    if (NOT DEFINED BOOTSTRAPPED_DLL)
        target_compile_definitions(${FILE_STEM} PRIVATE BOOTSTRAPPED_DLL="${CMAKE_CURRENT_SOURCE_DIR}/piggy/piggy.dll")
    else()
        target_compile_definitions(${FILE_STEM} PRIVATE BOOTSTRAPPED_DLL="${BOOTSTRAPPED_DLL}")
    endif()
    if (GENERATE_TEST)
        add_executable(dllloader dllloader.cpp)
        add_subdirectory(piggy "${CMAKE_CURRENT_SOURCE_DIR}/piggy")
    endif()
endif()
