cmake_minimum_required(VERSION 3.29)
project(Example4 CXX)
set(CMAKE_CXX_STANDARD 23)

if (NOT DEFINED OUT_PATH)
    set(OUT_PATH "${CMAKE_BINARY_DIR}")
endif()

if (VERBOSE)
    add_compile_definitions(IS_VERBOSE)
endif()
include_directories("${CMAKE_CURRENT_SOURCE_DIR}/../../../include" "${CMAKE_CURRENT_SOURCE_DIR}/SysWhispers3")
#set(LIBS "libvcruntime.lib" "libcmt.lib" "ucrt.lib" "kernel32.lib" "msvcprt.lib" )# "msvcprt.lib" "libcpmt.lib" "ucrtd.lib"

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(LIBS "libvcruntimed.lib" "libcmtd.lib" "ucrtd.lib" "kernel32.lib" "msvcprtd.lib")
else()
    set(LIBS "libvcruntime.lib" "libcmt.lib" "ucrt.lib" "kernel32.lib" "msvcprt.lib")
endif()

if (GENERATE_BOOTSTRAP)
    if (NOT DEFINED BOOTSTRAPPER_BUILD_DIR)
        set(BOOTSTRAPPER_BUILD_DIR "${CMAKE_CURRENT_SOURCE_DIR}/build-bootstrapper")
    endif()
    add_executable(bootstrapper main.cpp)
    target_compile_definitions(bootstrapper PRIVATE
            IS_BOOTSTRAP="${GENERATE_BOOTSTRAP}"
            OUT_PATH="${BOOTSTRAPPER_BUILD_DIR}"
    )
    target_link_options(bootstrapper PRIVATE "/NODEFAULTLIB" "/MACHINE:X64")
    target_link_libraries(bootstrapper PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/SysWhispers3/build/syscalls.lib")
    target_link_libraries(bootstrapper PRIVATE "${LIBS}")
else()
    enable_language(ASM_NASM)
    if (NOT EXISTS "${OUT_PATH}/bootstrap.txt")
        message(FATAL_ERROR "Please build and run the generator half first.")
    else()
        file(STRINGS "${OUT_PATH}/bootstrap.txt" FILE_STEM)
        list(GET FILE_STEM 0 FILE_STEM)
    endif()
    add_library(${FILE_STEM} SHARED main.cpp "${OUT_PATH}/${FILE_STEM}.asm")
    set_target_properties(${FILE_STEM} PROPERTIES
            LINK_FLAGS "/DEF:\"${OUT_PATH}/${FILE_STEM}.def\""
    )
    target_compile_definitions(${FILE_STEM} PRIVATE OUT_PATH="${OUT_PATH}")
    target_link_options(${FILE_STEM} PRIVATE "/NODEFAULTLIB" "/MACHINE:X64")
    target_link_libraries(${FILE_STEM} PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/SysWhispers3/build/syscalls.lib")
    target_link_libraries(${FILE_STEM} PRIVATE "${LIBS}")
    if (GENERATE_TEST)
        add_executable(dllloader dllloader.cpp)
        add_subdirectory(piggy "${CMAKE_CURRENT_SOURCE_DIR}/piggy")
        file(WRITE "${OUT_PATH}/dlls.txt" "${CMAKE_CURRENT_SOURCE_DIR}/piggy/piggy.dll\n")
        target_link_options(dllloader PRIVATE "/NODEFAULTLIB" "/MACHINE:X64")
        target_link_libraries(dllloader PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/SysWhispers3/build/syscalls.lib")
        target_link_libraries(dllloader PRIVATE "${LIBS}")
    endif()
endif()
