cmake_minimum_required(VERSION 3.29)
project(bootstrapper CXX ASM_NASM)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "Standard libraries for C" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "Standard libraries for C++" FORCE)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(LIBS "libvcruntimed.lib" "libcmtd.lib" "ucrtd.lib" "kernel32.lib" "msvcprtd.lib")
else()
    set(LIBS "libvcruntime.lib" "libcmt.lib" "ucrt.lib" "kernel32.lib" "msvcprt.lib")
endif()

if (NOT EXISTS "${OUT_PATH}/bootstrap.txt")
    message(FATAL_ERROR "Please build and run the generator half first.")
else()
    file(STRINGS "${OUT_PATH}/bootstrap.txt" FILE_STEM)
    list(GET FILE_STEM 0 FILE_STEM)
endif()

add_library(${FILE_STEM} SHARED ../main.cpp "${OUT_PATH}/${FILE_STEM}.asm")
target_include_directories(${FILE_STEM} PRIVATE "${PMO_INCLUDE}" "${SW3_SRC_DIR}")
set_target_properties(${FILE_STEM} PROPERTIES
        LINK_FLAGS "/DEF:\"${OUT_PATH}/${FILE_STEM}.def\""
)
target_compile_definitions(${FILE_STEM} PRIVATE OUT_PATH="${OUT_PATH}")
target_compile_options(${FILE_STEM} PRIVATE $<$<COMPILE_LANGUAGE:C>:-Zp8>)
target_compile_options(${FILE_STEM} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Zp8>)
target_link_options(${FILE_STEM} PRIVATE "/NODEFAULTLIB" "/MACHINE:X64" "/subsystem:console")
target_link_libraries(${FILE_STEM} PRIVATE "${SW3_BIN_DIR}/syscalls.lib")
target_link_libraries(${FILE_STEM} PRIVATE "${LIBS}")
if (DEFINED GENERATE_TEST AND GENERATE_TEST)
    cmake_path(SET PARENT_CURRENT_SOURCE_DIR NORMALIZE "${CMAKE_CURRENT_SOURCE_DIR}/..")
    add_executable(dllloader "${PARENT_CURRENT_SOURCE_DIR}/dllloader.cpp")
    target_link_libraries(dllloader PRIVATE "${SW3_BIN_DIR}/syscalls.lib")
    target_link_options(dllloader PRIVATE "/NODEFAULTLIB" "/MACHINE:X64" "/subsystem:console")
    target_link_libraries(dllloader PRIVATE "${LIBS}")
endif()
