cmake_minimum_required(VERSION 3.29)
project(bootstrapper CXX ASM_NASM)
set(CMAKE_CXX_STANDARD 23)

set(CMAKE_C_STANDARD_LIBRARIES "" CACHE STRING "Standard libraries for C" FORCE)
set(CMAKE_CXX_STANDARD_LIBRARIES "" CACHE STRING "Standard libraries for C++" FORCE)
string(TOUPPER "${CMAKE_BUILD_TYPE}" uppercase_CMAKE_BUILD_TYPE)

if (uppercase_CMAKE_BUILD_TYPE STREQUAL "DEBUG")
    set(LIBS "libvcruntimed.lib" "libcmtd.lib" "ucrtd.lib" "kernel32.lib" "msvcprtd.lib")
else ()
    set(LIBS "libvcruntime.lib" "libcmt.lib" "ucrt.lib" "kernel32.lib" "msvcprt.lib")
endif()

if (NOT EXISTS "${OUT_PATH}/bootstrap.txt" OR NOT DEFINED DLL_NAME)
    message(WARNING "Please build and run the generator half first.")
else ()
    file(STRINGS "${OUT_PATH}/bootstrap.txt" FILE_STEM)
    list(GET FILE_STEM 0 FILE_STEM)

    add_library(${FILE_STEM} SHARED "${CMAKE_CURRENT_SOURCE_DIR}/main.cpp" "${OUT_PATH}/${FILE_STEM}.asm")
    target_include_directories(${FILE_STEM} PRIVATE "${PMO_INCLUDE}" "${SW3_SRC_DIR}" "${CMAKE_CURRENT_SOURCE_DIR}/../include")
    set_target_properties(${FILE_STEM} PROPERTIES LINK_FLAGS "/DEF:\"${OUT_PATH}/${FILE_STEM}.def\"")
    target_compile_definitions(${FILE_STEM} PRIVATE OUT_PATH="${OUT_PATH}")
    target_compile_options(${FILE_STEM} PRIVATE $<$<COMPILE_LANGUAGE:C>:-Zp8>)
    target_compile_options(${FILE_STEM} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:-Zp8>)
    target_link_options(${FILE_STEM} PRIVATE "/NODEFAULTLIB" "/MACHINE:X64" "/subsystem:console")
    target_link_libraries(${FILE_STEM} PRIVATE "${SW3_BIN_DIR}/syscalls.lib")
    target_link_libraries(${FILE_STEM} PRIVATE "${LIBS}")
    set_target_properties(${FILE_STEM} PROPERTIES MSVC_RUNTIME_CHECKS "")

    if (NOT uppercase_CMAKE_BUILD_TYPE STREQUAL "DEBUG")
        if (CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND MSVC)
            target_compile_definitions(${FILE_STEM} PRIVATE "$<$<COMPILE_LANGUAGE:C>:/clang:-m64 /clang:-O3 /clang:-march=native /WX- /Gy /clang:-flto /clang:-fomit-frame-pointer>")
        elseif (MSVC)
            target_compile_definitions(${FILE_STEM} PRIVATE "$<$<COMPILE_LANGUAGE:C>:/O2 /Ox /Ob2 /Ot /Oy /Oi /WX- /GL /Gy /Gm- /MP>")
        endif()
        target_link_options(${FILE_STEM} PRIVATE "$<$<COMPILE_LANGUAGE:C>:/OPT:REF /OPT:ICF=3 /LTCG /DEBUG:NONE /EMITPOGOPHASEINFO>")
        target_compile_definitions(${FILE_STEM} PRIVATE OPTIMIZATIONS_ON)
    endif()

    if (DEFINED GENERATE_TEST)
        add_compile_definitions(DLL_NAME="${CMAKE_CURRENT_BINARY_DIR}/${DLL_NAME}")
        add_subdirectory(piggy)
    endif()
endif()